скачать файл из гугл диска
moevm/mse1h2024-cv-tasks pull request #40
Opened 2024-04-01 11:52 UTC by WukAp

2024-04-01 11:52 UTC, WukAp commented
вики тут
https://github.com/moevm/mse1h2024-cv-tasks/wiki/%D0%A1%D0%BA%D0%B0%D1%87%D0%B0%D1%82%D1%8C-%D1%84%D0%B0%D0%B9%D0%BB-%D0%B8%D0%B7-%D0%BE%D0%B1%D0%BB%D0%B0%D1%87%D0%BD%D0%BE%D0%B3%D0%BE-%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D0%B0/_edit

2024-04-01 11:54 UTC, WukAp commented
у меня сейчас ссылка на файл берётся из директории actions'а, чтобы он брался из корня проекта, как задумано, надо передавать ссылку в докерфайл через переменные или тома в гитфлоу

2024-04-01 16:06 UTC, Homry requested changes

2024-04-01 16:06 UTC, Homry commented on .github/actions/run-metrics/Dockerfile
>  # Очистка кэша apt-get
model_link.txt

2024-04-08 17:06 UTC, YariKar commented
Неверное название пулл-реквеста.

2024-04-08 19:47 UTC, YariKar commented
Пасибо, что исправила README)

2024-04-08 19:57 UTC, WukAp commented
![image](https://github.com/moevm/mse1h2024-cv-tasks/assets/47060627/db48512d-427e-47bf-8c5a-86b642b2ecb4)
пруфы, что всё скачал и успешно завершился

2024-04-08 19:59 UTC, Margo63 commented
https://github.com/moevm/mse1h2024-cv-tasks/issues/44)[https://github.com/moevm/mse1h2024-cv-tasks/issues/44

2024-04-08 20:00 UTC, WukAp commented
> #44



> #44

2024-04-08 20:04 UTC, zwphyro commented on .github/workflows/README.md
> +`apt-get update && apt-get install -y curl gpg && curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg && echo
Стоит добавить переносы строк перед и после этой строки.

2024-04-21 12:24 UTC, merged